--drop table producenci;
--drop table stan_magazynu;
--drop table etaty;
--drop table hurtownie;
--drop table klienci;
--drop table pozycja_zamowienia;
--drop table pracownicy;
--drop table produkt;
--drop table reklamacje;
--drop table zwroty;
--drop table zespoly;
--drop table produkt_z_hurtowni;

create table producenci(
NIP char(10) PRIMARY KEY not null,
nazwa_firmy varchar(20) not null,
adres varchar(20) not null,
nr_telefonu char(9) not null
);

alter table producenci modify nr_telefonu constraint un_nrtelefonuProducenta unique;

create table stan_magazynu(
nr_produktu INT PRIMARY KEY,
nazwa_firmy varchar(20) not null,
ilosc number(3)not null,
nazwa_produktu varchar(20) not null
);

create table produkt(
id_produktu INT PRIMARY KEY,
kategoria VARCHAR(20)not null,
nazwa_produktu VARCHAR(20) not null,
producent VARCHAR(15) not null,
cena float(5) not null,
nazwa_dystrybutora varchar(15) not null,
opis_produktu varchar(80) not null,
NIP char(10) not null,
nr_produktu int not null,
constraint fk_produkt1 foreign key(NIP) references producenci(NIP),
constraint fk_produkt2 foreign key(nr_produktu) references stan_magazynu(nr_produktu)
);
alter table produkt modify nazwa_dystrybutora varchar(40);
alter table produkt modify producent varchar(40);

create table hurtownie(
NIP char(10) PRIMARY KEY not null,
nazwa_firmy varchar(20) not null,
rodzaj_produktu varchar(20) not null,
adres varchar(20) not null,
nr_telefonu char(9) not null, 
nazwa_produktu varchar(20) not null
);


create table klienci(
nr_klienta number(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null,
imie varchar(20) not null,
nazwisko varchar(20) not null,
nr_telefonu char(9) not null,
email varchar(40) not null,
newsletter number(1) null
);


create table reklamacje(
nr_reklamacji int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null,
czy_uznana number(1) not null,
forma_reklamacji varchar(30) not null
);

create table transakcje(
nr_transakcji int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null,
kwota_sum float(6) not null, 
data_transakcji  DATE DEFAULT CURRENT_DATE NOT NULL,
forma_platnosci varchar(10) not null,
nr_pracownika int not null,
nr_klienta number(10) not null,
nr_reklamacji number(10) null,
constraint fk_transakcje1 foreign key (nr_klienta) references klienci(nr_klienta),
constraint fk_transakcje2 foreign key (nr_reklamacji) references reklamacje(nr_reklamacji),
constraint fk_transakcje3 foreign key (nr_pracownika) references pracownicy(nr_pracownika) 
);


create table pozycja_zamowienia(
nr_pozycji int not null,
id_produktu int not null,
liczba int not null, 
cena_jednostkowa float(5) not null,
nr_transakcji number(10) not null,
constraint fk_pozycja1 foreign key(nr_transakcji) references transakcje(nr_transakcji),
constraint fk_pozycja2 foreign key(id_produktu) references produkt(id_produktu)
);


create table etaty(
nazwa_etatu varchar(40) not null,
placa_min float(4) not null,
placa_max float(4) not null
);
alter table etaty add constraint pk_nazwaetatu primary key(nazwa_etatu);


create table zespoly(
nr_zespolu int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null,
nazwa_zespolu varchar(20) not null
);


create table pracownicy(
nr_pracownika int PRIMARY KEY not null,
pesel char(11) not null,
imie varchar(20) not null,
nazwisko varchar(20) not null,
drugie_imie varchar(20) null,
nazwa_etatu varchar(40) not null,
placa_pod float(4) not null,
placa_dod float(4) null,
zatrudniony_kiedy DATE NOT NULL,
nr_szefa int null,
nr_zespolu int not null
);

alter table pracownicy modify pesel constraint un_pesel unique;
alter table pracownicy add constraint fk_pracownicy_01 foreign key(nazwa_etatu) references etaty(nazwa_etatu);
alter table pracownicy add constraint fk_pracownicy_02 foreign key(nr_zespolu) references zespoly(nr_zespolu) ON DELETE CASCADE;



create table zwroty(
nr_reklamacji int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null,
nr_transakcji int not null,
constraint uk_nr_transakcji  unique(nr_transakcji)
);

create table produkt_z_hurtowni(
NIP char(10) not null,
id_produktu int not null
);

alter table produkt_z_hurtowni add constraint fk_produkt_hurtownia_01 foreign key(NIP) references hurtownie(NIP);
alter table produkt_z_hurtowni add constraint fk_produkt_hurtownia_02 foreign key(id_produktu) references produkt(id_produktu);